import { ImageListProps } from "@/types/type";

export const mockImageData: ImageListProps[] = [
  {
    collections: 15,
    comments: 2,
    downloads: 120,
    id: 123456,
    imageHeight: 1080,
    imageSize: 204800,
    imageWidth: 1920,
    largeImageURL: "https://example.com/large-image.jpg",
    likes: 50,
    pageURL: "https://example.com/page-url",
    previewHeight: 150,
    previewURL: "https://example.com/preview-url.jpg",
    previewWidth: 150,
    tags: "액션가면,초코비",
    type: "photo",
    user: "신짱구",
    userImageURL: "https://example.com/user-image-url.jpg",
    user_id: 78910,
    views: 1000,
    webformatHeight: 300,
    webformatURL: "https://example.com/webformat-url.jpg",
    webformatWidth: 400,
  },
  {
    collections: 10,
    comments: 5,
    downloads: 200,
    id: 789012,
    imageHeight: 720,
    imageSize: 102400,
    imageWidth: 1280,
    largeImageURL: "https://example.com/large-image2.jpg",
    likes: 75,
    pageURL: "https://example.com/page-url2",
    previewHeight: 100,
    previewURL: "https://example.com/preview-url2.jpg",
    previewWidth: 100,
    tags: "영어,학생,모에피",
    type: "photo",
    user: "김철수",
    userImageURL: "https://example.com/user-image-url2.jpg",
    user_id: 12345,
    views: 2000,
    webformatHeight: 250,
    webformatURL: "https://example.com/webformat-url2.jpg",
    webformatWidth: 350,
  },
];
