import { ImageListProps } from "@/types/type";

export const mockImageData: Partial<ImageListProps>[] = [
  {
    collections: 15,
    comments: 2,
    downloads: 120,
    id: 123456,
    imageHeight: 1440,
    imageSize: 204800,
    imageWidth: 2560,
    largeImageURL: "/shin_pic.jpg",
    likes: 50,
    pageURL: "/shin_pic.jpg",
    previewHeight: 150,
    previewURL: "/shin_pic.jpg",
    previewWidth: 150,
    tags: "액션가면,초코비",
    type: "photo",
    user: "신짱구",
    userImageURL: "/shin_profile.jpg",
    user_id: 78910,
    views: 1000,
    webformatHeight: 300,
    webformatURL: "/shin_pic.jpg",
    webformatWidth: 400,
  },
  {
    collections: 10,
    comments: 5,
    downloads: 200,
    id: 789012,
    imageHeight: 1433,
    imageSize: 102400,
    imageWidth: 1000,
    largeImageURL: "/shin_profile.jpg",
    likes: 75,
    pageURL: "/shin_profile.jpg",
    previewHeight: 100,
    previewURL: "/shin_profile.jpg",
    previewWidth: 100,
    tags: "영어,학생,모에피",
    type: "photo",
    // user: "김철수",
    userImageURL: "",
    user_id: 12345,
    views: 2000,
    webformatHeight: 250,
    webformatURL: "./shin_profile.jpg",
    webformatWidth: 350,
  },
];
